image: restra/golang-docker-gitlabci

variables:
  MAIN_IMAGE_NAME: weautomateeverything/gofidogo

services:
  - docker:dind

stages:
  - build
  - upgrade

before_script:
  - mkdir -p /go/src/gitlab.com/automateEverything/goFidoGo
  - cp -r . /go/src/gitlab.com/automateEverything/goFidoGo
  - cd /go/src/gitlab.com/automateEverything/goFidoGo

build:
  stage: build
  script:
    - go get -v
    - go build
    - docker login -u weautomateeverything -p $DOCKER_PASSWORD docker.com
    - docker build -t $MAIN_IMAGE_NAME:latest .
    - docker build -t $MAIN_IMAGE_NAME:$CI_COMMIT_REF_NAME .
    - docker push $MAIN_IMAGE_NAME:latest
    - docker push $MAIN_IMAGE_NAME:$CI_COMMIT_REF_NAME
