image: golang:latest

variables:
  BIN_NAME: goFidoGo
  ARTIFACTS_DIR: artifacts
  GO_PROJECT: gitlab.com/automateEverything/goFidoGo

stages:
  - build
  - test

before_script:
  - mkdir -p ${GOPATH}/src/${GO_PROJECT}
  - mkdir -p ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
  - cd ${GOPATH}/src/${GO_PROJECT}
  - go get -v

build-my-project:
  stage: build
  script:
    - go build -o ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/${BIN_NAME}
  artifacts:
    paths:
      - ${ARTIFACTS_DIR}

test-my-project:
  stage: test
  script:
    - go test -v -cover ./...