image: gitlab/dind


variables:
  CONTAINER_TEST_IMAGE: hub.docker.com/weautomateeverything/goFidoGo:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: hub.docker.com/weautomateeverything/goFidoGo:latest

before_script:
  - docker login -u weautomateeverything -p $DOCKER_PASSWORD hub.docker.com
build:
  stage: build
  script:
  - docker run --rm -v "$(pwd):/src" -v /var/run/docker.sock:/var/run/docker.sock -e COMPRESS_BINARY=true centurylink/golang-builder $CONTAINER_TEST_IMAGE
  - docker push $CONTAINER_TEST_IMAGE