apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: fido
  name: fido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fido
  template:
    metadata:
      labels:
        app: fido
    spec:
      containers:
      - image: weautomateeverything/gofidogo:12.1
        name: fido
        envFrom:
        - configMapRef:
            name: gofidogo
        - secretRef:
            name: gofidogo
